package com.empowerly.repository;

import com.empowerly.model.AppointmentLetter;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AppointmentLetterRepository extends MongoRepository<AppointmentLetter, String> {

    // Find all appointment letters generated by a specific HR
    List<AppointmentLetter> findByGeneratedByIdOrderByGeneratedAtDesc(String generatedById);

    // Find all appointment letters
    List<AppointmentLetter> findAllByOrderByGeneratedAtDesc();

    // Find by employee name
    List<AppointmentLetter> findByEmployeeNameContainingIgnoreCase(String employeeName);
}
