package com.empowerly.repository;

import com.empowerly.model.OfferLetter;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OfferLetterRepository extends MongoRepository<OfferLetter, String> {

    // Find all offer letters generated by a specific HR
    List<OfferLetter> findByGeneratedByIdOrderByGeneratedAtDesc(String generatedById);

    // Find all offer letters
    List<OfferLetter> findAllByOrderByGeneratedAtDesc();

    // Find by employee name
    List<OfferLetter> findByEmployeeNameContainingIgnoreCase(String employeeName);
}
